    MainForm.setObjectName(_fromUtf8("MainForm"))
    MainForm.resize(281, 120)
    MainWindow.browseButton = QtGui.QPushButton(MainForm)
    MainWindow.browseButton.setGeometry(QtCore.QRect(150, 30, 51, 21))
    MainWindow.browseButton.setFlat(False)
    MainWindow.browseButton.setObjectName(_fromUtf8("browseButton"))
    MainWindow.ouputText = QtGui.QLineEdit(MainForm)
    MainWindow.ouputText.setGeometry(QtCore.QRect(10, 30, 141, 20))
    MainWindow.ouputText.setObjectName(_fromUtf8("ouputText"))
    MainWindow.label = QtGui.QLabel(MainForm)
    MainWindow.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
    MainWindow.label.setObjectName(_fromUtf8("label"))
    MainWindow.label_2 = QtGui.QLabel(MainForm)
    MainWindow.label_2.setGeometry(QtCore.QRect(10, 60, 91, 16))
    MainWindow.label_2.setObjectName(_fromUtf8("label_2"))
    MainWindow.formatBox = QtGui.QComboBox(MainForm)
    MainWindow.formatBox.setGeometry(QtCore.QRect(120, 80, 69, 22))
    MainWindow.formatBox.setObjectName(_fromUtf8("formatBox"))
    MainWindow.formatBox.addItem(_fromUtf8(""))
    MainWindow.formatBox.addItem(_fromUtf8(""))
    MainWindow.formatBox.addItem(_fromUtf8(""))
    MainWindow.formatBox.addItem(_fromUtf8(""))
    MainWindow.formatBox.addItem(_fromUtf8(""))
    MainWindow.label_3 = QtGui.QLabel(MainForm)
    MainWindow.label_3.setGeometry(QtCore.QRect(120, 60, 61, 16))
    MainWindow.label_3.setObjectName(_fromUtf8("label_3"))
    MainWindow.delayBox = QtGui.QDoubleSpinBox(MainForm)
    MainWindow.delayBox.setGeometry(QtCore.QRect(10, 80, 81, 22))
    MainWindow.delayBox.setDecimals(3)
    MainWindow.delayBox.setMinimum(0.001)
    MainWindow.delayBox.setMaximum(999999.999)
    MainWindow.delayBox.setSingleStep(5.0)
    MainWindow.delayBox.setProperty("value", 5.0)
    MainWindow.delayBox.setObjectName(_fromUtf8("delayBox"))
    MainWindow.mainButton = QtGui.QPushButton(MainForm)
    MainWindow.mainButton.setGeometry(QtCore.QRect(210, 10, 61, 41))
    MainWindow.mainButton.setObjectName(_fromUtf8("mainButton"))
    MainWindow.stopButton = QtGui.QPushButton(MainForm)
    MainWindow.stopButton.setGeometry(QtCore.QRect(210, 60, 61, 41))
    MainWindow.stopButton.setObjectName(_fromUtf8("stopButton"))
    QtCore.QMetaObject.connectSlotsByName(MainForm)
    MainForm.setTabOrder(MainWindow.browseButton, MainWindow.delayBox)
    MainForm.setTabOrder(MainWindow.delayBox, MainWindow.formatBox)
    MainForm.setTabOrder(MainWindow.formatBox, MainWindow.mainButton)
    MainForm.setTabOrder(MainWindow.mainButton, MainWindow.stopButton)
    MainForm.setTabOrder(MainWindow.stopButton, MainWindow.ouputText)
    MainForm.setWindowTitle(QtGui.QApplication.translate("MainForm", "Title", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.browseButton.setText(QtGui.QApplication.translate("MainForm", "Browse", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.label.setText(QtGui.QApplication.translate("MainForm", "Output :", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.label_2.setText(QtGui.QApplication.translate("MainForm", "Delay (seconds) :", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.formatBox.setItemText(0, QtGui.QApplication.translate("MainForm", "png", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.formatBox.setItemText(1, QtGui.QApplication.translate("MainForm", "jpg", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.formatBox.setItemText(2, QtGui.QApplication.translate("MainForm", "mp4", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.formatBox.setItemText(3, QtGui.QApplication.translate("MainForm", "avi", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.formatBox.setItemText(4, QtGui.QApplication.translate("MainForm", "mov", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.label_3.setText(QtGui.QApplication.translate("MainForm", "Format:", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.mainButton.setText(QtGui.QApplication.translate("MainForm", "Start", None, QtGui.QApplication.UnicodeUTF8))
    MainWindow.stopButton.setText(QtGui.QApplication.translate("MainForm", "Stop", None, QtGui.QApplication.UnicodeUTF8))
